# Generated by Django 3.1.7 on 2021-03-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_venda', models.DateField(auto_now_add=True)),
                ('hora_venda', models.TimeField(auto_now_add=True)),
                ('data_hora_venda', models.DateTimeField(auto_now_add=True)),
                ('numero_venda', models.IntegerField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('comprovante_venda', models.FileField(upload_to='Comprovante_venda/')),
                ('email_cliente', models.EmailField(blank=True, max_length=254, null=True)),
                ('venda_concluida', models.BooleanField()),
                ('qtd_itens', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
