# Generated by Django 3.1.7 on 2021-04-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
        migrations.AddField(
            model_name='vendas',
            name='produtos',
            field=models.ManyToManyField(to='vendas.Produto'),
        ),
    ]
