# Generated by Django 3.1.7 on 2021-04-05 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_vendas_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email_cliente',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='vendas.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='comprovante_venda',
            field=models.FileField(upload_to='Comprovante_venda/', verbose_name='Comprovante de Venda'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='numero_venda',
            field=models.IntegerField(verbose_name='Número da venda'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='qtd_itens',
            field=models.IntegerField(blank=True, default=0, verbose_name='Quantidade de Itens Vendidos'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor total da venda'),
        ),
    ]
