# Generated by Django 3.1.7 on 2021-04-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_remove_vendas_email_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total da Venda'),
        ),
    ]
