# Generated by Django 3.1.7 on 2021-04-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_auto_20210404_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='venda_concluida',
            field=models.BooleanField(verbose_name='Venda Concluída'),
        ),
    ]
